### ISSUE TITLE
Enhancement:  add "proposed" or "future", based on release calendar, or somewhere else.

### ISSUE THREAD

**Issue by gregglind** [mozilla/product-details-json#4]
As always, seeing `https://product-details.mozilla.org/` is AWESOME.

I am now needing "future" or "proposed".  I am not sure whether to chase that from the tail or the head of the fox!  Ideas welcome.

**Comment by pmac** [comment]
This repo is just for mirroring and consuming product-details. It’d be best to file a bug with release management so that they can update the ship-it tool that generates the product-details JSON files.

**Comment by gregglind** [comment]
That sounds good to me!  Will do.
